# Generated by Django 2.0.3 on 2018-03-10 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uc', models.PositiveSmallIntegerField()),
                ('cod', models.CharField(max_length=35)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrollment', models.DateTimeField(auto_now_add=True)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnames', models.CharField(max_length=35)),
                ('names', models.CharField(max_length=35)),
                ('dni', models.CharField(max_length=35)),
                ('FechaNacimiento', models.DateField(max_length=35)),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('personaltype', models.CharField(choices=[('P', 'Profesor'), ('A', 'Alumno')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptos', models.PositiveSmallIntegerField()),
                ('id_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.Enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.Personal'),
        ),
        migrations.AddField(
            model_name='course',
            name='id_teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.Personal'),
        ),
    ]
