# Generated by Django 2.0.3 on 2018-03-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='FechaNacimiento',
            new_name='birthdate',
        ),
    ]
