# Generated by Django 2.0.3 on 2018-03-10 23:08

import control_academico.apps.gestionCursos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0002_auto_20180310_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_teachers',
            field=models.ForeignKey(db_column='Id_teachers', limit_choices_to=control_academico.apps.gestionCursos.models.limitoptions, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionCursos.Personal'),
        ),
    ]
