# Generated by Django 2.0.3 on 2018-03-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0003_auto_20180310_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_teachers',
            field=models.ForeignKey(db_column='Id_teachers', limit_choices_to=models.Q(pk__in=[2, 4, 6]), on_delete=django.db.models.deletion.DO_NOTHING, to='gestionCursos.Personal'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id_student',
            field=models.ForeignKey(db_column='Id_student', limit_choices_to=models.Q(pk__in=[1, 3, 5]), on_delete=django.db.models.deletion.DO_NOTHING, to='gestionCursos.Personal'),
        ),
    ]
