# Generated by Django 2.0.3 on 2018-03-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0004_auto_20180310_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cod',
            new_name='code',
        ),
    ]
