# Generated by Django 2.0.3 on 2018-03-12 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0005_auto_20180311_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnames', models.CharField(max_length=35)),
                ('names', models.CharField(max_length=35)),
                ('dni', models.CharField(max_length=35)),
                ('birthdate', models.DateField(max_length=35)),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('personaltype', models.CharField(choices=[('P', 'Profesor'), ('A', 'Alumno')], default='A', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id_student',
            field=models.ForeignKey(db_column='Id_student', limit_choices_to=models.Q(pk__in=[1, 3, 5, 7]), on_delete=django.db.models.deletion.DO_NOTHING, to='gestionCursos.Person'),
        ),
    ]
