# Generated by Django 2.0.3 on 2018-03-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0006_auto_20180312_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_teachers',
            field=models.ForeignKey(db_column='Id_teachers', limit_choices_to=models.Q(pk__in=[]), on_delete=django.db.models.deletion.DO_NOTHING, to='gestionCursos.Person'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id_student',
            field=models.ForeignKey(db_column='Id_student', limit_choices_to=models.Q(pk__in=[]), on_delete=django.db.models.deletion.DO_NOTHING, to='gestionCursos.Person'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
