# Generated by Django 2.0.3 on 2018-03-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0007_auto_20180312_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='id_student',
            field=models.ForeignKey(db_column='Id_student', limit_choices_to=models.Q(pk__in=[1, 2]), on_delete=django.db.models.deletion.DO_NOTHING, to='gestionCursos.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(max_length=35, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.CharField(max_length=35, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='person',
            name='names',
            field=models.CharField(max_length=35, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personaltype',
            field=models.CharField(choices=[('P', 'Profesor'), ('A', 'Alumno')], default='A', max_length=1, verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surnames',
            field=models.CharField(max_length=35, verbose_name='Apellido'),
        ),
    ]
