# Generated by Django 2.0.3 on 2018-03-12 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0008_auto_20180312_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='id_student',
            field=models.ForeignKey(db_column='Id_student', limit_choices_to=models.Q(pk__in=[1, 2, 3]), on_delete=django.db.models.deletion.DO_NOTHING, to='gestionCursos.Person'),
        ),
    ]
